### ISSUE TITLE
How to use Relu?

### ISSUE THREAD

**Issue by ippqw5** [rcpsl/DeepBern-Nets#1]
I set the `MODEL.ACTIVATION : relu` in `configs/mnist_FCNNb_clean.yml`.And following is the error:

Traceback (most recent call last):
  File "/content/DeepBern-Nets/train.py", line 532, in <module>
    train(
  File "/content/DeepBern-Nets/train.py", line 313, in train
    test_acc, cert_acc = test_robust(
  File "/content/DeepBern-Nets/test.py", line 105, in test_robust
    cert_cnt += robust_cnt
UnboundLocalError: local variable 'robust_cnt' referenced before assignment

I jumper into the `test.py` and find that it doesn't support `mode = ibp`(You commented out some code), only support `mode = bern` .
How can I fix it?

**Comment by haithamkhedr** [comment]
@ippqw5  Thanks for raising this issue, It should be fixed now. Please note that you might want to decrease the learning rate to get good accuracy with ReLU. The supported modes for evaluating certified robustness now are as follows:


(Activation, bounding method) -> can be configured using (`MODEL.ACTIVATION, ROBUSTNESS.BOUNDING_METHOD`)

-(`relu`, `clean`) ## just evaluates the test accuracy
-(`bern`, `clean`)
-(`relu`, `pgd`) ## Uses PGD
-(`bern`, `pgd`)
-(`bern`, `bern`) ##Uses Bern-IBP

-IBP can be supported for ReLU networks by installing [AutoLirpa](https://github.com/Verified-Intelligence/auto_LiRPA) library and uncommenting the commented test code. Will update the repo soon with this as well as supporting IBP for DeepBern-Nets.

Please let me know if this is helpful and if you have further questions.
